- hosts: localhost
  gather_facts: False
  roles:
    - role: firewall
      become: yes
    - role: cups
      become: yes
    - role: docker
      become: yes
    - role: nvidia
      become: yes
    - role: slurm
      become: yes
    - role: swap
      become: yes
    - role: uv
      become: yes
    - role: autokey
